"""
=========================================================
Homez OS

File : app/domains/orchestration/constants.py

자동 운영 상태(L, 2026-08-20) — 이 값들은 어떤 테이블에도 저장되지
않는다. 각 도메인(Order/Purchase/Shipment/ReturnOrder/Settlement)이
자기 상태의 단일 진실 공급원이며, 이 상수는 그 값들을 읽어 조합한
"현재 화면에 뭘 보여줄까"용 projection 결과 라벨일 뿐이다.
=========================================================
"""


class OrchestrationStage:

    PRODUCT_READY = "PRODUCT_READY"
    COUPANG_SUBMISSION_READY = "COUPANG_SUBMISSION_READY"
    ORDER_RECEIVED = "ORDER_RECEIVED"
    INVENTORY_RESERVED = "INVENTORY_RESERVED"
    SOURCING_REQUIRED = "SOURCING_REQUIRED"
    FULFILLMENT_READY = "FULFILLMENT_READY"
    PURCHASE_APPROVAL_REQUIRED = "PURCHASE_APPROVAL_REQUIRED"
    PURCHASE_SUBMITTED = "PURCHASE_SUBMITTED"
    SUPPLIER_CONFIRMED = "SUPPLIER_CONFIRMED"
    SHIPMENT_READY = "SHIPMENT_READY"
    SHIPPED = "SHIPPED"
    DELIVERED = "DELIVERED"
    SETTLEMENT_PENDING = "SETTLEMENT_PENDING"
    SETTLED = "SETTLED"

    # 예외
    PRODUCT_INPUT_REQUIRED = "PRODUCT_INPUT_REQUIRED"
    IMAGE_REQUIRED = "IMAGE_REQUIRED"
    CATEGORY_REQUIRED = "CATEGORY_REQUIRED"
    MARGIN_REVIEW_REQUIRED = "MARGIN_REVIEW_REQUIRED"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    SUPPLIER_REQUIRED = "SUPPLIER_REQUIRED"
    PRICE_CHANGED = "PRICE_CHANGED"
    PURCHASE_FAILED = "PURCHASE_FAILED"
    SHIPMENT_DELAYED = "SHIPMENT_DELAYED"
    RETURN_REQUESTED = "RETURN_REQUESTED"
    REFUND_REQUIRED = "REFUND_REQUIRED"
    RETRY_WAIT = "RETRY_WAIT"
    ESTOP_BLOCKED = "ESTOP_BLOCKED"
    USER_ACTION_REQUIRED = "USER_ACTION_REQUIRED"


__all__ = [
    "OrchestrationStage",
]
